services:
  - type: web
    name: personal-task-manager-backend
    env: python
    rootDir: Frontend/src/Backend
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: https://team-task-manag.netlify.app
